"""PHREEQC input drafting utilities for THMC MCP mock and live modes."""

from __future__ import annotations

from typing import Any


MAJOR_IONS = ("Ca", "Mg", "Na", "K", "HCO3", "SO4", "Cl")
RADIONUCLIDES = ("U", "Ra226", "Rn222", "Pb210", "Po210")


def _value_line(name: str, value: dict[str, Any]) -> str:
    amount = value.get("value")
    unit = value.get("unit", "")
    return f"    {name:<8} {amount} {unit}".rstrip()


def build_phreeqc_input_draft(
    *,
    project_id: str,
    model_id: str,
    scenario: str,
    water_samples: list[dict[str, Any]],
    mineral_assemblages: list[dict[str, Any]] | None = None,
    database: str = "phreeqc.dat",
    reaction_network: dict[str, Any] | None = None,
) -> tuple[str, list[str]]:
    """Create a conservative PHREEQC draft and warnings.

    The builder intentionally writes draft blocks only. It does not invent
    thermodynamic constants, decay constants, surface areas, or kinetic rates.
    """
    warnings = [
        "PHREEQC input is a draft generated from available MCP data; verify charge balance, units, database species, and thermodynamic constants before execution.",
    ]
    if database.lower() in {"phreeqc.dat", "llnl.dat"}:
        warnings.append(
            "Selected PHREEQC database may not contain complete uranium-series radionuclide species; validate database coverage before interpretation."
        )

    lines = [
        f"TITLE GeoMine THMC draft for {project_id} / {model_id}",
        f"# Scenario: {scenario}",
        f"# Database requested: {database}",
        "# Generated by geomine_thmc MCP; mock/live mode is reported outside this file.",
        "",
    ]

    for index, sample in enumerate(water_samples, start=1):
        field = sample.get("field_parameters", {})
        analytes = sample.get("lab_analytes", {})
        sample_id = sample.get("sample_id", f"sample-{index}")
        lines.extend(
            [
                f"SOLUTION {index} {sample_id}",
                f"    temp     {field.get('T_C', 25)}",
                f"    pH       {field.get('pH', 7)} charge",
            ]
        )
        eh = field.get("Eh_mV")
        if eh is not None:
            lines.append(f"    # Eh_mV   {eh}  # convert to pe with field method before final runs")
        for ion in MAJOR_IONS:
            if ion in analytes:
                lines.append(_value_line(ion, analytes[ion]))
        for nuclide in RADIONUCLIDES:
            if nuclide in analytes:
                lines.append(f"    # {nuclide:<6} {analytes[nuclide].get('value')} {analytes[nuclide].get('unit', '')}  # confirm PHREEQC species mapping")
        lines.append("")

    phases: list[str] = []
    for assemblage in mineral_assemblages or []:
        for mineral in assemblage.get("minerals", []):
            name = str(mineral.get("name", "")).strip()
            if name:
                phases.append(name)
    if phases:
        lines.append("EQUILIBRIUM_PHASES 1")
        for phase in sorted(set(phases)):
            lines.append(f"    {phase} 0 0  # draft saturation target; verify phase name in {database}")
        lines.append("")

    if reaction_network:
        lines.extend(
            [
                "# Reaction network notes",
                f"# redox_couples: {reaction_network.get('redox_couples', 'not supplied')}",
                f"# sorption_model: {reaction_network.get('sorption_model', 'not supplied')}",
                f"# kinetic_reactions: {reaction_network.get('kinetic_reactions', 'not supplied')}",
                "",
            ]
        )
    else:
        warnings.append("No explicit reaction_network payload supplied; PHREEQC draft omits kinetic, surface complexation, and ion-exchange blocks.")

    lines.extend(
        [
            "SELECTED_OUTPUT 1",
            "    -reset false",
            "    -pH true",
            "    -pe true",
            "    -alkalinity true",
            "    -totals U Ca Mg S(6) C(4)",
            "    -saturation_indices Calcite Quartz Goethite Barite",
            "",
            "END",
        ]
    )
    return "\n".join(lines), warnings
