"""PFLOTRAN planning and packaging MCP tools.

These tools do not execute PFLOTRAN. They build and validate planning
artifacts for the GeoMine PFLOTRAN Modeling skill family.
"""

from __future__ import annotations

import csv
import json
import re
from io import StringIO
from typing import Any

from ..provenance import provenance
from ..schemas import tool_response
from ..storage import THMCStorage, get_default_storage


REQUIRED_BLOCKS = ["SIMULATION", "SUBSURFACE", "END_SUBSURFACE"]
RECOMMENDED_BLOCKS = ["GRID", "REGION", "MATERIAL_PROPERTY", "CHEMISTRY", "OUTPUT"]


def _deck_skeleton(model_id: str, scenario: str, dimension: str, chemistry_mode: str) -> str:
    return f"""# PFLOTRAN input deck skeleton generated by GeoMine MCP.
# model_id: {model_id}
# scenario: {scenario}
# status: draft_not_executed

SIMULATION
  SIMULATION_TYPE SUBSURFACE
  PROCESS_MODELS
    SUBSURFACE_FLOW flow
      MODE <FLOW_MODE>
    /
    SUBSURFACE_TRANSPORT transport
      MODE {chemistry_mode}
    /
  /
END

SUBSURFACE
  GRID
    TYPE structured
    NXYZ <nx> <ny> <nz>
    BOUNDS
      <xmin> <ymin> <zmin>
      <xmax> <ymax> <zmax>
    /
  END

  REGION all
    COORDINATES
      <xmin> <ymin> <zmin>
      <xmax> <ymax> <zmax>
    /
  END

  MATERIAL_PROPERTY material_1
    ID 1
    POROSITY <porosity>
    PERMEABILITY
      PERM_ISO <permeability_m2>
    /
  END

  CHEMISTRY
    PRIMARY_SPECIES
      <primary_species>
    /
    SECONDARY_SPECIES
      <secondary_species>
    /
    MINERALS
      <minerals>
    /
  END

  OUTPUT
    FORMAT HDF5
    VARIABLES
      LIQUID_PRESSURE
      TOTAL_CONCENTRATION <species>
      PH
      POROSITY
    /
  END
END_SUBSURFACE
"""


def validate_pflotran_input_deck(input_deck: str) -> dict[str, Any]:
    upper = input_deck.upper()
    missing_required = [block for block in REQUIRED_BLOCKS if block not in upper]
    missing_recommended = [block for block in RECOMMENDED_BLOCKS if block not in upper]
    placeholders = sorted(set(re.findall(r"<[^>\n]+>", input_deck)))
    warnings = []
    if placeholders:
        warnings.append("Input deck contains placeholders and is not ready for execution.")
    if missing_recommended:
        warnings.append("Recommended PFLOTRAN blocks are missing or not detected.")
    return tool_response(
        tool="validate_pflotran_input_deck",
        query={"input_length": len(input_deck)},
        mode="mock",
        results=[
            {
                "valid_structure": not missing_required,
                "missing_required_blocks": missing_required,
                "missing_recommended_blocks": missing_recommended,
                "placeholder_count": len(placeholders),
                "placeholders": placeholders,
                "status": "draft_not_executed",
            }
        ],
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
        warnings=warnings + ["No PFLOTRAN executable was called."],
        ok=not missing_required,
    )


def build_pflotran_input_deck(
    project_id: str,
    model_id: str,
    scenario: str = "tailings_seepage",
    dimension: str = "2D",
    chemistry_mode: str = "reactive_transport",
    grid: dict[str, Any] | None = None,
    materials: list[dict[str, Any]] | None = None,
    chemistry: dict[str, Any] | None = None,
) -> dict[str, Any]:
    deck = _deck_skeleton(model_id, scenario, dimension, chemistry_mode)
    validation = validate_pflotran_input_deck(deck)["results"][0]
    manifest = {
        "package_type": "PFLOTRAN Modeling Package",
        "version": "0.1",
        "project_id": project_id,
        "model_id": model_id,
        "scenario": scenario,
        "solver_family": "PFLOTRAN",
        "process_modes": {
            "flow": "<FLOW_MODE>",
            "transport": chemistry_mode,
            "reactive_transport": chemistry_mode == "reactive_transport",
            "thermal": chemistry_mode in {"TH", "THC", "thermal_hydrologic_chemical"},
            "geomechanics": False,
        },
        "domain": {"dimension": dimension, "grid_type": "structured", "grid": grid or {}},
        "materials": materials or [],
        "chemistry": chemistry or {"database": "<database_file>", "primary_species": [], "minerals": []},
        "execution": {
            "input_file": f"{model_id}.in",
            "run_command": f"pflotran -pflotranin {model_id}.in",
            "status": "draft_not_executed",
        },
        "missing_data": validation.get("placeholders", []),
    }
    return tool_response(
        tool="build_pflotran_input_deck",
        query={"project_id": project_id, "model_id": model_id, "scenario": scenario, "dimension": dimension},
        mode="mock",
        results=[{"input_deck": deck, "manifest": manifest, "validation": validation}],
        assets=[
            {
                "asset_id": f"{model_id}-pflotran-input-deck",
                "asset_type": "pflotran_input_deck",
                "name": f"{model_id}.in",
                "format": "text/plain",
                "storage": "inline_mock",
            }
        ],
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock", solver="PFLOTRAN"),
        warnings=["Draft input deck skeleton only; no PFLOTRAN solver was executed."],
    )


def build_pflotran_run_manifest(
    model_name: str,
    input_file: str = "model.in",
    database_file: str = "",
    mpi_processes: int | None = None,
    expected_outputs: list[str] | None = None,
) -> dict[str, Any]:
    mpi = mpi_processes or 1
    command = f"pflotran -pflotranin {input_file}" if mpi <= 1 else f"mpirun -np {mpi} pflotran -pflotranin {input_file}"
    manifest = {
        "model_name": model_name,
        "input_file": input_file,
        "database_file": database_file,
        "run_command": command,
        "mpi_processes": mpi,
        "expected_outputs": expected_outputs or ["pflotran.out", "pflotran.h5", "observation.csv"],
        "status": "draft_not_executed",
    }
    return tool_response(
        tool="build_pflotran_run_manifest",
        query={"model_name": model_name, "input_file": input_file, "mpi_processes": mpi},
        mode="mock",
        results=[manifest],
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
        warnings=["Run manifest only; no PFLOTRAN process was started."],
    )


def parse_pflotran_observation_output(observation_text: str, delimiter: str = "auto") -> dict[str, Any]:
    if delimiter == "auto":
        delimiter = "\t" if observation_text.count("\t") > observation_text.count(",") else ","
    reader = csv.DictReader(StringIO(observation_text), delimiter=delimiter)
    rows = [dict(row) for row in reader]
    return tool_response(
        tool="parse_pflotran_observation_output",
        query={"input_length": len(observation_text), "delimiter": delimiter},
        mode="mock",
        results=[{"row_count": len(rows), "columns": reader.fieldnames or [], "rows": rows}],
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
        warnings=["Parsed text only; scientific interpretation requires run provenance and validation."],
    )


def build_pflotran_result_summary(observation_rows: list[dict[str, Any]]) -> dict[str, Any]:
    numeric: dict[str, list[float]] = {}
    for row in observation_rows:
        for key, value in row.items():
            try:
                number = float(value)
            except (TypeError, ValueError):
                continue
            numeric.setdefault(key, []).append(number)
    summary = {
        key: {"count": len(values), "min": min(values), "max": max(values), "last": values[-1]}
        for key, values in numeric.items()
        if values
    }
    return tool_response(
        tool="build_pflotran_result_summary",
        query={"row_count": len(observation_rows)},
        mode="mock",
        results=[{"numeric_summary": summary, "status": "parsed_not_validated"}],
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
        warnings=["Summary statistics only; no calibration or convergence check was performed."],
    )


def save_pflotran_model_package(
    project_id: str,
    package_label: str,
    package_spec: dict[str, Any],
    source_asset_ids: list[str] | None = None,
    notes: str = "",
    storage: THMCStorage | None = None,
) -> dict[str, Any]:
    store = storage or get_default_storage()
    package = store.save_pflotran_model_package(
        {
            "project_id": project_id,
            "package_label": package_label,
            "package_spec": package_spec,
            "source_asset_ids": source_asset_ids or [],
            "notes": notes,
        }
    )
    return tool_response(
        tool="save_pflotran_model_package",
        query={"project_id": project_id, "package_label": package_label},
        mode="mock",
        results=[package],
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
        warnings=["Stored a draft PFLOTRAN package record; not an executed model."],
    )


def get_pflotran_model_package(package_id: str, storage: THMCStorage | None = None) -> dict[str, Any]:
    store = storage or get_default_storage()
    package = store.get_pflotran_model_package(package_id)
    if not package:
        return tool_response(
            tool="get_pflotran_model_package",
            query={"package_id": package_id},
            mode="error",
            ok=False,
            provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
            errors=[
                {
                    "code": "PFLOTRAN_PACKAGE_NOT_FOUND",
                    "message": "PFLOTRAN model package was not found in the local registry.",
                    "retryable": False,
                    "suggested_action": "Save a PFLOTRAN package first or check package_id.",
                }
            ],
        )
    return tool_response(
        tool="get_pflotran_model_package",
        query={"package_id": package_id},
        mode="mock",
        results=[package],
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
    )


def list_pflotran_model_packages(project_id: str | None = None, storage: THMCStorage | None = None) -> dict[str, Any]:
    store = storage or get_default_storage()
    packages = store.list_pflotran_model_packages(project_id=project_id)
    return tool_response(
        tool="list_pflotran_model_packages",
        query={"project_id": project_id},
        mode="mock",
        results=packages,
        provenance=provenance("GeoMine PFLOTRAN MCP planner", mode="mock"),
    )
